name: Friday AM

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * 5"

jobs:
  Push: 
   runs-on: ubuntu-latest
   steps:
    - name: what's the time
      run: date
    - name: "webgl-fundamentals"
      run: echo "Triangle Render"
    - name: "jsfiddle"
      run: echo "render triangle"